### ISSUE TITLE
Error when get package

### ISSUE THREAD

**Issue by yusmi25** [dreampowder/strava_flutter#71]
hello @dreampowder , I'm Using Flutter 2.5.3 (Android SDK version 31.0.0) when I implement this package, I get the error : 

`Running "flutter pub get" in qoolbike_v1...                     
Because image_picker >=0.8.4 depends on image_picker_platform_interface ^2.3.0 which depends on http ^0.13.0, image_picker >=0.8.4 requires http ^0.13.0.
So, because qoolbike_v1 depends on both image_picker ^0.8.4 and http ^0.12.2, version solving failed.
pub get failed (1; So, because qoolbike_v1 depends on both image_picker ^0.8.4 and http ^0.12.2, version solving failed.)
exit code 1`

I would be really grateful for any help
Thank you.

**Comment by harkairt** [comment]
try with

```
dependencies:
  strava_flutter: ^1.2.2+62
  ...

dependency_overrides:
  http: ^0.13.0
```
