### ISSUE TITLE
Incompatibility with flutterflow dependencies

### ISSUE THREAD

**Issue by diegohsi** [dreampowder/strava_flutter#91]
@dreampowder 
I'm doing an integration with Strava using flutterflow.
I'm getting a lot of errors from versions that are not compatible with the latest version of the strava_flutter lib.
I saw that the master already has the update of the libs sent on 01/24/2023.
Please, when are you going to publish this version of the package in pub.dev?

`pubspec.yml`
```
name: xxx
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  auto_size_text: 3.0.0
  built_collection: 5.1.1
  built_value: 8.4.0
  cached_network_image: 3.2.1
  cloud_firestore: 4.2.0
  cloud_firestore_platform_interface: 5.9.1
  cloud_firestore_web: 3.1.1
  firebase_auth: 4.2.0
  firebase_auth_platform_interface: 6.11.4
  firebase_auth_web: 5.2.0
  firebase_core: 2.4.0
  firebase_core_platform_interface: 4.5.2
  firebase_core_web: 2.0.2
  flutter_animate: 1.0.0
  flutter_cache_manager: 3.3.0
  font_awesome_flutter: 10.1.0
  from_css_color: 2.0.0
  go_router: 3.1.0
  google_fonts: 3.0.1
  google_sign_in: 5.4.0
  google_sign_in_ios: 5.4.0
  google_sign_in_platform_interface: 2.2.0
  google_sign_in_web: 0.10.2
  intl: 0.17.0
  json_path: 0.4.1
  json_serializable: 6.3.1
  page_transition: 2.0.4
  plugin_platform_interface: 2.1.3
  provider: 6.0.4
  rxdart: 0.27.4
  shared_preferences: 2.0.15
  sign_in_with_apple: 4.1.0
  sign_in_with_apple_platform_interface: 1.0.0
  sign_in_with_apple_web: 1.0.1
  smooth_page_indicator: 1.0.0+2
  sqflite: 2.2.0+2
  timeago: 3.2.2
  url_launcher: 6.1.5
  strava_flutter: ^1.2.2+62


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0

dev_dependencies:
  build_runner: 2.2.0
  built_value_generator: 8.4.0

  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/fonts/
    - assets/images/
    - assets/videos/
    - assets/audios/
    - assets/lottie_animations/
    - assets/rive_animations/
    - assets/pdfs/


  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
```
Output console when run `pub get`
```
Because strava_flutter >=1.2.1+55 depends on url_launcher ^5.4.5 and depends on url_launcher 6.1.5, strava_flutter >=1.2.1+55 is forbidden.
So, because depends on strava_flutter ^1.2.2+62, version solving failed.
pub get failed (1; So, because xxx depends on strava_flutter ^1.2.2+62, version solving failed.)
```
